experiments:
  - dataset_size: 0.1
    learning_rate: 1e-3
    epochs: 5
  - dataset_size: 0.3
    learning_rate: 1e-4
    epochs: 10
  - dataset_size: 0.5
    learning_rate: 5e-5
    epochs: 15
  - dataset_size: 1.0
    learning_rate: 1e-5
    epochs: 20
