dataset:
  root: "/app/data/common-voice"
  max_samples: null # Set to limit dataset size

audio:
  sr: 16000
  clip_duration: 5.0
  max_clips: 5

model:
  embed_dim: 768
  num_classes: 0 # Will be set automatically
  nhead: 8
  dim_feedforward: 2048
  dropout: 0.1
  transformer_layers: 6

training:
  batch_size: 32
  lr: 1e-4
  epochs: 20
  device: "cuda"

output:
  model_dir: ./models/
